/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package heimdall;

import javax.swing.JOptionPane;

/**
 *
 * @author guilherme
 */
public class JNovoUsuario extends javax.swing.JFrame {

    
    /**
     * Creates new form JNovoUsuario
     */
    
    private Usuario usuario;
    private TratarEntrada trata;

    public JNovoUsuario() {
        initComponents();
    }
    
    public JNovoUsuario(Usuario usuario) {
        this.usuario = usuario;
        this.trata = new TratarEntrada();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfLogin = new javax.swing.JTextField();
        bCdtUsuario = new javax.swing.JButton();
        bCancelUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Usuario");
        setPreferredSize(new java.awt.Dimension(386, 187));

        jLabel1.setText("Login de Usuário*: ");

        jLabel3.setText("Nome Completo*: ");

        tfNome.setToolTipText("Digite o nome completo do usuário");
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeKeyPressed(evt);
            }
        });

        tfLogin.setToolTipText("Digite o nome de login que será utilizado por esse usuário");
        tfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLoginKeyPressed(evt);
            }
        });

        bCdtUsuario.setText("Cadastrar Usuário");
        bCdtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCdtUsuarioActionPerformed(evt);
            }
        });

        bCancelUsuario.setText("Cancelar");
        bCancelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelUsuarioActionPerformed(evt);
            }
        });

        jTextPane1.setBackground(jLabel1.getBackground());
        jTextPane1.setBorder(null);
        jTextPane1.setText("Não é permitido o uso de caracteres especiais ou  acentos no login de usuário, com excessão do  ponto (.) e underline (_). ");
        jScrollPane2.setViewportView(jTextPane1);

        jLabel2.setText("CPF*: ");

        jTextField1.setToolTipText("Digite o CPF do novo usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCdtUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelUsuario))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfLogin)
                                .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jTextField1)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCdtUsuario)
                    .addComponent(bCancelUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(385, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCdtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCdtUsuarioActionPerformed
        cadastrar();
    }//GEN-LAST:event_bCdtUsuarioActionPerformed

    private void bCancelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelUsuarioActionPerformed
        int resp = JOptionPane.showConfirmDialog(null,"Você tem certeza que deseja cancelar as alterações feitas?","Tem certeza?",JOptionPane.YES_NO_OPTION);
        if(resp==0){
            dispose();
        }
    }//GEN-LAST:event_bCancelUsuarioActionPerformed

    private void tfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastrar();
        }
    }//GEN-LAST:event_tfNomeKeyPressed

    private void tfLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLoginKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cadastrar();
        }
    }//GEN-LAST:event_tfLoginKeyPressed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed
    
    public void cadastrar(){
        String campo = "";
        
        if(tfNome.getText().length()!=0){
            campo += tfNome.getText().charAt(0);
        }
        if(!trata.whiteList(campo)){
            JOptionPane.showMessageDialog(null,"Nome completo inválido.");
        } else if(!trata.whiteList(tfLogin.getText())){
            JOptionPane.showMessageDialog(null,"O login contem caracteres inválidos ou está vazio. Por favor, digite novamente.");
        } else{
            int resp = JOptionPane.showConfirmDialog(null,"Você tem certeza que deseja cadastrar esse usuário?\nNome:"+tfNome.getText()+"\nLogin: "+tfLogin.getText(),"Tem certeza?",JOptionPane.YES_NO_OPTION);
            if(resp==0){
                ExecutaSQL sql = new ExecutaSQL();
                SenhaAutomatica senha = new SenhaAutomatica(6);
                Usuario user = new Usuario();
                
                user.setLogin(tfLogin.getText());
                user.setNome(tfNome.getText());
                user.setNivel(2);
                user.setSenha(senha.senhaSemiAutomatica(tfLogin.getText()));

                if(sql.SELECT_USUARIO("de_login_usuario", "'"+user.getLogin()+"'")!=null){
                    JOptionPane.showMessageDialog(null,"Já existe alguém cadastrado com esse login. Tente outro.");
                    return;
                }

                sql = new ExecutaSQL();

                if(!sql.INSERT_USUARIO(user)){
                    JOptionPane.showMessageDialog(null,"Cadastrado com sucesso\nLogin: "+user.getLogin()+"\nSenha: "+senha.getSenhaSimples());
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Falha no cadastrado.");
                }
            }
        }
        
        
    }
    
    public void fecharJanelas(){
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelUsuario;
    private javax.swing.JButton bCdtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
