/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heimdall.Forms;

import heimdall.ExecutaSQL;
import heimdall.Util.Modelo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme
 */
public class JComponente extends javax.swing.JFrame {

    private ArrayList<Modelo> m;
    private String[] colunas = new String [] {"N°", "Modelo", "Marca", "Layout", "Classe"};
    private DefaultTableModel dtm;
    
    /**
     * Creates new form JComponente
     */
    public JComponente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lpIdtVeiculo = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        tfComponente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpObs = new javax.swing.JTextPane();
        cbModelo = new javax.swing.JComboBox();
        bCustomModelo = new javax.swing.JButton();
        bRefreshModelo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfDataValComponente = new javax.swing.JTextField();
        tpComponente = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tComponente = new javax.swing.JTable();
        tbVeiculo = new javax.swing.JToolBar();
        bSaveCdtComponente = new javax.swing.JButton();
        bNewCdtComponente = new javax.swing.JButton();
        bEditCdtComponente = new javax.swing.JButton();
        bDeleteCdtComponente = new javax.swing.JButton();
        bRefreshCdtComponente = new javax.swing.JButton();
        bCancelCdtComponente = new javax.swing.JButton();
        tbHelpCdtComponente = new javax.swing.JToggleButton();
        lpCondVeiculo = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTagRfid = new javax.swing.JTextField();
        tfDataCdt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextPane1.setEditable(false);
        jScrollPane2.setViewportView(jTextPane1);

        lpIdtVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Veículo"));
        lpIdtVeiculo.setToolTipText("");
        lpIdtVeiculo.setName(""); // NOI18N
        lpIdtVeiculo.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel1.setText("Modelo*: ");

        tfComponente.setToolTipText("Escreva o nome do veiculo. EX: Onibus 05");

        jLabel2.setText("Descrição: ");

        jLabel3.setText("Nome*: ");

        tpObs.setPreferredSize(new java.awt.Dimension(5, 25));
        jScrollPane1.setViewportView(tpObs);

        cbModelo.setModel(new javax.swing.DefaultComboBoxModel(carregarModelos()));
        cbModelo.setToolTipText("Escolha o modelo do veículo");

        bCustomModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 32x32/Customize.png"))); // NOI18N
        bCustomModelo.setToolTipText("Customizar Modelos");
        bCustomModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCustomModeloActionPerformed(evt);
            }
        });

        bRefreshModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 32x32/refresh.png"))); // NOI18N
        bRefreshModelo.setToolTipText("Atualizar Lista de Modelos");
        bRefreshModelo.setPreferredSize(new java.awt.Dimension(32, 32));
        bRefreshModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshModeloActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Validade: ");

        tfDataValComponente.setToolTipText("Escreva o nome do veiculo. EX: Onibus 05");

        javax.swing.GroupLayout lpIdtVeiculoLayout = new javax.swing.GroupLayout(lpIdtVeiculo);
        lpIdtVeiculo.setLayout(lpIdtVeiculoLayout);
        lpIdtVeiculoLayout.setHorizontalGroup(
            lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpIdtVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1)
                    .addGroup(lpIdtVeiculoLayout.createSequentialGroup()
                        .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfComponente)
                            .addGroup(lpIdtVeiculoLayout.createSequentialGroup()
                                .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bRefreshModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCustomModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpIdtVeiculoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDataValComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        lpIdtVeiculoLayout.setVerticalGroup(
            lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpIdtVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpIdtVeiculoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bCustomModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(bRefreshModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lpIdtVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDataValComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        lpIdtVeiculo.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(tfComponente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(cbModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(bCustomModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(bRefreshModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpIdtVeiculo.setLayer(tfDataValComponente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tComponente.setAutoCreateRowSorter(true);
        tComponente.setModel(dtm);
        tComponente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tComponente);

        tpComponente.addTab("Componentes", jScrollPane3);

        tbVeiculo.setFloatable(false);
        tbVeiculo.setRollover(true);

        bSaveCdtComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/save.png"))); // NOI18N
        bSaveCdtComponente.setToolTipText("Salvar Alterações");
        bSaveCdtComponente.setFocusable(false);
        bSaveCdtComponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSaveCdtComponente.setPreferredSize(new java.awt.Dimension(50, 50));
        bSaveCdtComponente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbVeiculo.add(bSaveCdtComponente);

        bNewCdtComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/new-file.png"))); // NOI18N
        bNewCdtComponente.setToolTipText("Novo Cadastro");
        bNewCdtComponente.setFocusable(false);
        bNewCdtComponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNewCdtComponente.setPreferredSize(new java.awt.Dimension(50, 50));
        bNewCdtComponente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNewCdtComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewCdtComponenteActionPerformed(evt);
            }
        });
        tbVeiculo.add(bNewCdtComponente);

        bEditCdtComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/TextEdit.png"))); // NOI18N
        bEditCdtComponente.setToolTipText("Editar Cadastro");
        bEditCdtComponente.setFocusable(false);
        bEditCdtComponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEditCdtComponente.setPreferredSize(new java.awt.Dimension(50, 50));
        bEditCdtComponente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbVeiculo.add(bEditCdtComponente);

        bDeleteCdtComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/delete.png"))); // NOI18N
        bDeleteCdtComponente.setToolTipText("Deletar Cadastro");
        bDeleteCdtComponente.setFocusable(false);
        bDeleteCdtComponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDeleteCdtComponente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbVeiculo.add(bDeleteCdtComponente);

        bRefreshCdtComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/refresh.png"))); // NOI18N
        bRefreshCdtComponente.setToolTipText("Atualizar Lista");
        bRefreshCdtComponente.setFocusable(false);
        bRefreshCdtComponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bRefreshCdtComponente.setPreferredSize(new java.awt.Dimension(50, 50));
        bRefreshCdtComponente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bRefreshCdtComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshCdtComponenteActionPerformed(evt);
            }
        });
        tbVeiculo.add(bRefreshCdtComponente);

        bCancelCdtComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/cancel.png"))); // NOI18N
        bCancelCdtComponente.setFocusable(false);
        bCancelCdtComponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCancelCdtComponente.setPreferredSize(new java.awt.Dimension(50, 50));
        bCancelCdtComponente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCancelCdtComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelCdtComponenteActionPerformed(evt);
            }
        });
        tbVeiculo.add(bCancelCdtComponente);

        tbHelpCdtComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/help.png"))); // NOI18N
        tbHelpCdtComponente.setFocusable(false);
        tbHelpCdtComponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbHelpCdtComponente.setPreferredSize(new java.awt.Dimension(50, 50));
        tbHelpCdtComponente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbVeiculo.add(tbHelpCdtComponente);

        lpCondVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Cadastro"));

        jLabel7.setText("Tag RFID*: ");

        jLabel8.setText("Data Cdt.: ");

        tfDataCdt.setEditable(false);
        tfDataCdt.setFocusable(false);
        tfDataCdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataCdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lpCondVeiculoLayout = new javax.swing.GroupLayout(lpCondVeiculo);
        lpCondVeiculo.setLayout(lpCondVeiculoLayout);
        lpCondVeiculoLayout.setHorizontalGroup(
            lpCondVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpCondVeiculoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(lpCondVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addGroup(lpCondVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTagRfid)
                    .addComponent(tfDataCdt, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap())
        );
        lpCondVeiculoLayout.setVerticalGroup(
            lpCondVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpCondVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpCondVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTagRfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lpCondVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfDataCdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lpCondVeiculo.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpCondVeiculo.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpCondVeiculo.setLayer(tfTagRfid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpCondVeiculo.setLayer(tfDataCdt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lpIdtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lpCondVeiculo)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tpComponente, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lpCondVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lpIdtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tpComponente, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCustomModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCustomModeloActionPerformed
        //jm.setVisible(true);
    }//GEN-LAST:event_bCustomModeloActionPerformed

    private void bRefreshModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshModeloActionPerformed
        //cbModelo.setModel(new javax.swing.DefaultComboBoxModel(carregarModelos()));
    }//GEN-LAST:event_bRefreshModeloActionPerformed

    private void bNewCdtComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewCdtComponenteActionPerformed

    }//GEN-LAST:event_bNewCdtComponenteActionPerformed

    private void bRefreshCdtComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshCdtComponenteActionPerformed

    }//GEN-LAST:event_bRefreshCdtComponenteActionPerformed

    private void bCancelCdtComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelCdtComponenteActionPerformed

      /*  int resp = JOptionPane.showConfirmDialog(null,"Você tem certeza que deseja cancelar as alterações feitas?","Tem certeza?",JOptionPane.YES_NO_OPTION);
        if(resp==0){
            jm.dispose();
            dispose();
        }*/
    }//GEN-LAST:event_bCancelCdtComponenteActionPerformed

    private void tfDataCdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataCdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataCdtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JComponente().setVisible(true);
            }
        });
    }
    
    public String[] carregarModelos(){
        ExecutaSQL sql = new ExecutaSQL();
        m = new ArrayList<Modelo>();
        m = sql.SELECT_ALL_MODELO_VEICULO();
        String[] modelos = new String[m.size()+1];
        
        modelos[0] = "";
        for(int i=1; i<=m.size(); i++){
            modelos[i] = m.get(i-1).getModelo();
        }
        
        return modelos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelCdtComponente;
    private javax.swing.JButton bCustomModelo;
    private javax.swing.JButton bDeleteCdtComponente;
    private javax.swing.JButton bEditCdtComponente;
    private javax.swing.JButton bNewCdtComponente;
    private javax.swing.JButton bRefreshCdtComponente;
    private javax.swing.JButton bRefreshModelo;
    private javax.swing.JButton bSaveCdtComponente;
    private javax.swing.JComboBox cbModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLayeredPane lpCondVeiculo;
    private javax.swing.JLayeredPane lpIdtVeiculo;
    private javax.swing.JTable tComponente;
    private javax.swing.JToggleButton tbHelpCdtComponente;
    private javax.swing.JToolBar tbVeiculo;
    private javax.swing.JTextField tfComponente;
    private javax.swing.JTextField tfDataCdt;
    private javax.swing.JTextField tfDataValComponente;
    private javax.swing.JTextField tfTagRfid;
    private javax.swing.JTabbedPane tpComponente;
    private javax.swing.JTextPane tpObs;
    // End of variables declaration//GEN-END:variables
}
