/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package heimdall.forms;

import heimdall.ExecutaSQL;
import heimdall.util.Classe;
import heimdall.util.Modelo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme
 */
public class JModelo extends javax.swing.JDialog {

    /**
     * Creates new form JModelo
     */
    
    private boolean classe;
    private ArrayList<Classe> classes;
    private int operacao = 0; // 1 = Novo registro; 2 = Atualizar um registro
    private boolean killThread = false;
    
    public JModelo(boolean classe/*true - Veiculo; false - componente*/) {
        setModal(true); //Faz com que o sistema aguarde a conclusão do JDialog para seguir com a execução. 
        this.classe = classe;
        initComponents();
        initTable();
        new Campos().start();
        liberarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbModelo = new javax.swing.JToolBar();
        bSaveCdtModelo = new javax.swing.JButton();
        bNewCdtModelo = new javax.swing.JButton();
        bEditCdtModelo = new javax.swing.JButton();
        bDeleteCdtVeiculo = new javax.swing.JButton();
        bRefreshCdtModelo = new javax.swing.JButton();
        bCancelCdtModelo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfModelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbClasse = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLayout = new javax.swing.JTextField();
        tpModelo = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tfLinhasTabela = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tModelo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Customizar Modelo");
        setMinimumSize(new java.awt.Dimension(627, 353));

        tbModelo.setFloatable(false);
        tbModelo.setRollover(true);

        bSaveCdtModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/save.png"))); // NOI18N
        bSaveCdtModelo.setToolTipText("Salvar Alterações");
        bSaveCdtModelo.setEnabled(false);
        bSaveCdtModelo.setFocusable(false);
        bSaveCdtModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSaveCdtModelo.setPreferredSize(new java.awt.Dimension(50, 50));
        bSaveCdtModelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSaveCdtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveCdtModeloActionPerformed(evt);
            }
        });
        tbModelo.add(bSaveCdtModelo);

        bNewCdtModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/new-file.png"))); // NOI18N
        bNewCdtModelo.setToolTipText("Novo Cadastro");
        bNewCdtModelo.setFocusable(false);
        bNewCdtModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNewCdtModelo.setPreferredSize(new java.awt.Dimension(50, 50));
        bNewCdtModelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNewCdtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewCdtModeloActionPerformed(evt);
            }
        });
        tbModelo.add(bNewCdtModelo);

        bEditCdtModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/TextEdit.png"))); // NOI18N
        bEditCdtModelo.setToolTipText("Editar Cadastro");
        bEditCdtModelo.setFocusable(false);
        bEditCdtModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEditCdtModelo.setPreferredSize(new java.awt.Dimension(50, 50));
        bEditCdtModelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbModelo.add(bEditCdtModelo);

        bDeleteCdtVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/delete.png"))); // NOI18N
        bDeleteCdtVeiculo.setToolTipText("Deletar Cadastro");
        bDeleteCdtVeiculo.setFocusable(false);
        bDeleteCdtVeiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDeleteCdtVeiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbModelo.add(bDeleteCdtVeiculo);

        bRefreshCdtModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/refresh.png"))); // NOI18N
        bRefreshCdtModelo.setToolTipText("Atualizar Lista");
        bRefreshCdtModelo.setFocusable(false);
        bRefreshCdtModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bRefreshCdtModelo.setPreferredSize(new java.awt.Dimension(50, 50));
        bRefreshCdtModelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bRefreshCdtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshCdtModeloActionPerformed(evt);
            }
        });
        tbModelo.add(bRefreshCdtModelo);

        bCancelCdtModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heimdall/img/icons 50x50/cancel.png"))); // NOI18N
        bCancelCdtModelo.setToolTipText("Cancelar e Sair");
        bCancelCdtModelo.setFocusable(false);
        bCancelCdtModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCancelCdtModelo.setPreferredSize(new java.awt.Dimension(50, 50));
        bCancelCdtModelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCancelCdtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelCdtModeloActionPerformed(evt);
            }
        });
        tbModelo.add(bCancelCdtModelo);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        tfModelo.setEnabled(false);

        jLabel1.setText("Modelo*: ");

        tfMarca.setEnabled(false);

        jLabel2.setText("Marca*: ");

        cbClasse.setModel(new javax.swing.DefaultComboBoxModel(carregarClasses(classe) ));
        cbClasse.setEnabled(false);

        jLabel4.setText("Classe*: ");

        jLabel3.setText("Layout*: ");

        tfLayout.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMarca)
                    .addComponent(tfModelo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfLayout)
                    .addComponent(cbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfLinhasTabela.setEditable(false);

        tModelo.setAutoCreateRowSorter(true);
        tModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Modelo", "Layout", "Marca", "Classe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tModelo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tModelo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tModelo);
        if (tModelo.getColumnModel().getColumnCount() > 0) {
            tModelo.getColumnModel().getColumn(0).setPreferredWidth(100);
            tModelo.getColumnModel().getColumn(1).setPreferredWidth(130);
            tModelo.getColumnModel().getColumn(2).setResizable(false);
            tModelo.getColumnModel().getColumn(2).setPreferredWidth(170);
            tModelo.getColumnModel().getColumn(3).setPreferredWidth(130);
            tModelo.getColumnModel().getColumn(4).setPreferredWidth(130);
        }

        jLabel5.setText("Nº");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLinhasTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLinhasTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        tpModelo.addTab("Modelos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpModelo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpModelo)
                .addContainerGap())
        );

        tpModelo.getAccessibleContext().setAccessibleName("Modelos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelCdtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelCdtModeloActionPerformed
        int resp = JOptionPane.showConfirmDialog(null,"Você tem certeza que deseja cancelar as alterações?","Tem certeza?",JOptionPane.YES_NO_OPTION);
        if(resp==0){
            killThread = true;
            dispose();
        }
    }//GEN-LAST:event_bCancelCdtModeloActionPerformed

    private void bNewCdtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewCdtModeloActionPerformed
        operacao = 1;
        liberarCampos(true);
    }//GEN-LAST:event_bNewCdtModeloActionPerformed

    private void bSaveCdtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveCdtModeloActionPerformed
        switch (operacao) {
            case 1:
                cadastrarNovo();
                break;
            case 2:
                
                break;
        }
    }//GEN-LAST:event_bSaveCdtModeloActionPerformed

    private void bRefreshCdtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshCdtModeloActionPerformed
        initTable();
    }//GEN-LAST:event_bRefreshCdtModeloActionPerformed
    
    private Classe[] carregarClasses(boolean tipo){
        ExecutaSQL sql = new ExecutaSQL();
        classes = new ArrayList<Classe>();
        classes = sql.SELECT_CLASSE_TIPO(tipo);
        Classe c[] = new Classe[classes.size()+1];
        
        c[0] = null;
        for(int i=1;i<=classes.size();i++){
            c[i] = classes.get(i-1);
        }
        return c;
    }
    
    private void liberarCampos(boolean b){
        tfModelo.setText("");
        tfLayout.setText("");
        tfMarca.setText("");
        cbClasse.setSelectedItem(null);
        
        tfModelo.setEnabled(b);
        tfLayout.setEnabled(b);
        tfMarca.setEnabled(b);
        cbClasse.setEnabled(b);
    }
    
    private void initTable(){
        try{
            ExecutaSQL sql = new ExecutaSQL();
            ArrayList<Modelo> aux = new ArrayList<Modelo>();
            DefaultTableModel dtm = (DefaultTableModel) tModelo.getModel();

            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }

            aux = sql.SELECT_MODELO_TIPO_CLASSE(classe);
            Object valores[] = new Object[aux.size()];
            for(int i=0; i<aux.size(); i++){
                String classe = (aux.get(i).getClasse() != null) ? aux.get(i).getClasse().getNome() : null;

                dtm.addRow(new Object[] {
                    aux.get(i).getCodigo(),
                    aux.get(i).getModelo(),
                    aux.get(i).getLayout(),
                    aux.get(i).getMarca(),
                    classe}
                );
            }     
            tModelo.setModel(dtm);
            tfLinhasTabela.setText(Integer.toString(dtm.getRowCount()));
        }catch(Exception ex){
            new JErro(true, ex, true, true, false);
        }
    }
    
    private void cadastrarNovo(){
        ExecutaSQL sql = new ExecutaSQL();
        Modelo m =  new Modelo();
        Classe classe = (Classe) cbClasse.getSelectedItem();
        
        if(classe!=null){
            m.setLayout(tfLayout.getText());
            m.setMarca(tfMarca.getText());
            m.setModelo(tfModelo.getText());
            m.setClasse(classe);
            
            if(!sql.INSERT_MODELO(m)){
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso.");
                liberarCampos(false);
            }else{
                JOptionPane.showMessageDialog(null,"Falha no cadastrado.");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Escolha a classe do seu veículo.");
        }
        
        initTable();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelCdtModelo;
    private javax.swing.JButton bDeleteCdtVeiculo;
    private javax.swing.JButton bEditCdtModelo;
    private javax.swing.JButton bNewCdtModelo;
    private javax.swing.JButton bRefreshCdtModelo;
    private javax.swing.JButton bSaveCdtModelo;
    private javax.swing.JComboBox cbClasse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tModelo;
    private javax.swing.JToolBar tbModelo;
    private javax.swing.JTextField tfLayout;
    private javax.swing.JTextField tfLinhasTabela;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTabbedPane tpModelo;
    // End of variables declaration//GEN-END:variables

    public class Campos extends Thread{
        public void run(){
            while(!killThread){
                verificarCampos();
            }
        }
        
        public void verificarCampos(){
            Classe classe = (Classe) cbClasse.getSelectedItem();
            int aux = tfModelo.getText().compareTo("");
            aux *= tfLayout.getText().compareTo("");
            aux *= tfMarca.getText().compareTo("");
            if(aux==0 || classe==null){
                bSaveCdtModelo.setEnabled(false);
            }else{
                bSaveCdtModelo.setEnabled(true);
            }
        }
    }

}
