/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heimdall.Forms;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme
 */
public class JSelecionaItem extends javax.swing.JDialog {
    private String tituloJanela;
    private String tituloID;
    private String tituloDenominacao;
    private ArrayList<SelecionaItem> itens = new ArrayList<SelecionaItem>();
    private Object objetoSelecionado;
    
    /**
     * Creates new form JSelecionaItem
     */
    public JSelecionaItem() {
        setModal(true);
        tituloJanela = "";
        tituloID = "";
        tituloDenominacao = "";
        initComponents();
    }

    public JSelecionaItem(String tituloJanela, String tituloID, String tituloDenominacao, boolean modal) {
        setModal(modal);
        this.tituloJanela = tituloJanela;
        this.tituloID = tituloID;
        this.tituloDenominacao = tituloDenominacao;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfLinhasTabela = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tItem = new javax.swing.JTable();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(tituloJanela);

        tfLinhasTabela.setEditable(false);

        jLabel9.setText("Nº");

        tItem.setAutoCreateRowSorter(true);
        tItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tItem.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tItem);
        if (tItem.getColumnModel().getColumnCount() > 0) {
            tItem.getColumnModel().getColumn(0).setPreferredWidth(100);
            tItem.getColumnModel().getColumn(0).setHeaderValue(tituloID);
            tItem.getColumnModel().getColumn(1).setPreferredWidth(295);
            tItem.getColumnModel().getColumn(1).setHeaderValue(tituloDenominacao);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLinhasTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfLinhasTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 47, Short.MAX_VALUE)))
        );

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOk)
                    .addComponent(bCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        objetoSelecionado = selectedItem();
        
        if(objetoSelecionado==null){
            JOptionPane.showMessageDialog(null, "É necessário selecionar um item");
            return;
        }
        
        dispose();
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSelecionaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSelecionaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSelecionaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSelecionaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JSelecionaItem dialog = new JSelecionaItem();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void add(int id, String denominacao, Object objeto){
        if(existsId(id)){
            new JErro(true, "Já existe um item com este id na lista de seleção.", false, true, false);
            return;
        }
            
        itens.add(new SelecionaItem(id, denominacao, objeto));
        initTable();
    }
    
    public boolean existsId(int id){
        for(int i=0; i<itens.size(); i++){
            if(itens.get(i).getId() == id) 
                return true;
        }
        
        return false;
    }
    
    public Object selectedItem(){
        if(tItem.getSelectedRow()<0)
            return null;
        
        for(int i=0; i<itens.size(); i++){
            if(itens.get(i).getId() == (int)tItem.getValueAt(tItem.getSelectedRow(), 0)) 
                return itens.get(i).getObjeto();
        }
        
        return null;
    }
    
    public void removeItem(int id){
        for(int i=0; i<itens.size(); i++){
            if(itens.get(i).getId() == id)
                itens.remove(i);
                
        }
        initTable();
    }
    
    private void initTable(){
        try{
            DefaultTableModel dtm = (DefaultTableModel) tItem.getModel();

            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }

            for(int i=0; i<itens.size(); i++){            
                dtm.addRow(new Object[] {
                    itens.get(i).getId(),
                    itens.get(i).getDenominacao()}
                );
            }     
            tItem.setModel(dtm);
            tfLinhasTabela.setText(Integer.toString(dtm.getRowCount()));
        }catch(Exception ex){
            new JErro(true, ex, true, true, false);
        }
    }

    public String getTituloJanela() {
        return tituloJanela;
    }

    public void setTituloJanela(String tituloJanela) {
        this.tituloJanela = tituloJanela;
    }

    public String getTituloID() {
        return tituloID;
    }

    public void setTituloID(String tituloID) {
        this.tituloID = tituloID;
    }

    public String getTituloDenominacao() {
        return tituloDenominacao;
    }

    public void setTituloDenominacao(String tituloDenominacao) {
        this.tituloDenominacao = tituloDenominacao;
    }

    public Object getObjetoSelecionado() {
        return objetoSelecionado;
    }

    public void setObjetoSelecionado(Object objetoSelecionado) {
        this.objetoSelecionado = objetoSelecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tItem;
    private javax.swing.JTextField tfLinhasTabela;
    // End of variables declaration//GEN-END:variables
    private class SelecionaItem{
        private int id; 
        private String denominacao;
        private Object objeto;
        

        public SelecionaItem() {
            this.id = 0;
            this.denominacao = "";
            this.objeto = null;
        }

        public SelecionaItem(int id, String denominacao, Object objeto) {
            this.id = id;
            this.denominacao = denominacao;
            this.objeto = objeto;
        }

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

        public String getDenominacao() {
            return denominacao;
        }

        public void setDenominacao(String denominacao) {
            this.denominacao = denominacao;
        }

        public Object getObjeto() {
            return objeto;
        }

        public void setObjeto(Object objeto) {
            this.objeto = objeto;
        }
    }
}
